update for rails 5 and ruby 2.4.1
ramhoj/time-zone-article pull request #3
Opened 2017-09-11 16:00 UTC by bhfailor

Made changes to that tests can be run with rails 5.1.4 and ruby 2.4.1.

Commit message should say 'rails 5'.

2017-09-12 08:02 UTC, ramhoj requested changes
Looks great, thank you!

Please resolve the conflicts and have a look at my comment regarding the bundler version and we can merge this :)

2017-09-12 08:02 UTC, ramhoj commented on Gemfile.lock
> +   1.16.0.pre.2
Tiny nit-pick: Can we bundle with latest stable bundler version?

2017-09-12 08:04 UTC, ramhoj commented
Oh, one more thing. Can you also update the README with the new [Ruby and Rails versions](https://github.com/ramhoj/time-zone-article#ruby-and-rails-version)?

2017-11-25 00:38 UTC, bhfailor commented
I think I have responded to your feedback, @ramhoj -
* bundler not prerelease
* update README
* resolved conflicts
* and also updated Travis ruby version

2017-11-27 08:59 UTC, ramhoj commented
Looks great @bhfailor, thank you!

2017-11-27 08:59 UTC, merged

2017-11-27 13:23 UTC, bhfailor commented
You're welcome, @ramhoj - thanks for sharing this work with the rest of us.

2017-11-27 14:52 UTC, ramhoj commented
🙂